### ISSUE TITLE
Sapeli binaries for Macintosh and Windows

### ISSUE THREAD

**Issue by yellow-panther** [SamuraiDangyo/Sapeli#1]
Hello Samurai Django,
it would be surely be a good idea to host both binaries of Tony Mokonen (Windows) and Spill The Tea (Mac OS) here - cf. forum www.talkchess.com

Is the own GUI for playing only for Linux available?

Regards,

**Comment by SamuraiDangyo** [comment]
Hello!
You are absolutely correct!
Credit where credit is due!

I linked the binary in readme.md.

About Sapeli 1.0. There was just 1 stupid mgen bug. It affected only one chess960 position where opponent's slider is in corner... My bad. Otherwise stable release.
I'm not providing binaries anymore. 

The Sapeli GUI is just a console gui. Very minimal but it you can play a game or match Sapeli vs Sapeli.
A game against Sapeli-ai.
> ./sapeli -setgamemode 1 -game

I'm not developing a graphical GUI.

xboard is my choice for graphical GUI. 

Regards.

**Comment by yellow-panther** [comment]
Toni, here are the Mac OS binaries by Jase de Lace a.k.a. Spill The Tea: https://drive.google.com/file/d/1pt08axuqk3OPJOVLHE0rwVLkDheV7NtZ/view 

He said: "I Finally Figured out how to share a single file through google drive.
It is a 7zip file of the entire source code (current master branch : 22 April 2019), which includes an additional folder entitled "MacOS_Binaries," with the simple modifications we discussed earlier (but you can also view Sapeli.c for specifics because I think you slightly changed it from when I first viewed it). 
I played around with the optimization, and I actually preferred O3 vs O2 optimization just from using the suite testing you have built in. I included two binaries: x64 and bmi2 builds (I added -mbmi2 -mpopcnt -msse3 flags to the makefile to do so). BMI2 builds typically perform better on mac, which is why I include it. "

XBoard/WinBoard-interface cf. http://www.computer-chess.org/doku.php?id=computer_chess:wiki:lists:gui_protocol_support_list

Regards,
